// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCon(arg1:string):Promise<string>;

export function DeleteItem(arg1:string,arg2:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function EditServer(arg1:string):Promise<string>;

export function GetFileSize(arg1:string,arg2:string):Promise<string>;

export function GetIpInfo():Promise<string>;

export function GetListServer():Promise<string>;

export function GetOneServer(arg1:number):Promise<string>;

export function KillPort(arg1:string):Promise<string>;

export function MoveOrCopyFolderAndFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function NewCon(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function NewFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PostNewPath(arg1:string,arg2:string,arg3:number):Promise<string>;

export function PostRadio():Promise<string>;

export function RemoveServer(arg1:number):Promise<string>;

export function RenameFolderOrFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveFile(arg1:Record<string, any>):Promise<string>;

export function SaveNewFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveServer(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectJavaExeDirect():Promise<string>;

export function SelectPath(arg1:string,arg2:boolean):Promise<string>;

export function SendNormal(arg1:string,arg2:string):Promise<string>;

export function SendRaw(arg1:string,arg2:string):Promise<void>;

export function SendResize(arg1:number,arg2:number,arg3:string):Promise<void>;

export function UploadDirOrFile(arg1:string,arg2:string,arg3:string):Promise<string>;
