// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCon(arg1) {
  return window['go']['main']['App']['CloseCon'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function EditServer(arg1) {
  return window['go']['main']['App']['EditServer'](arg1);
}

export function GetFileSize(arg1, arg2) {
  return window['go']['main']['App']['GetFileSize'](arg1, arg2);
}

export function GetIpInfo() {
  return window['go']['main']['App']['GetIpInfo']();
}

export function GetListServer() {
  return window['go']['main']['App']['GetListServer']();
}

export function GetOneServer(arg1) {
  return window['go']['main']['App']['GetOneServer'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function MoveOrCopyFolderAndFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MoveOrCopyFolderAndFile'](arg1, arg2, arg3, arg4, arg5);
}

export function NewCon(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NewCon'](arg1, arg2, arg3, arg4);
}

export function NewFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewFolder'](arg1, arg2, arg3);
}

export function PostNewPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostNewPath'](arg1, arg2, arg3);
}

export function PostRadio() {
  return window['go']['main']['App']['PostRadio']();
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RenameFolderOrFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolderOrFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveNewFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveNewFile'](arg1, arg2, arg3, arg4);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectJavaExeDirect() {
  return window['go']['main']['App']['SelectJavaExeDirect']();
}

export function SelectPath(arg1, arg2) {
  return window['go']['main']['App']['SelectPath'](arg1, arg2);
}

export function SendNormal(arg1, arg2) {
  return window['go']['main']['App']['SendNormal'](arg1, arg2);
}

export function SendRaw(arg1, arg2) {
  return window['go']['main']['App']['SendRaw'](arg1, arg2);
}

export function SendResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendResize'](arg1, arg2, arg3);
}

export function UploadDirOrFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDirOrFile'](arg1, arg2, arg3);
}
